import { Product } from "./types"

export const PROVINCIAS_ESPANA = [
  "A Coruna",
  "Alava",
  "Albacete",
  "Alicante",
  "Almeria",
  "Asturias",
  "Avila",
  "Badajoz",
  "Barcelona",
  "Burgos",
  "Caceres",
  "Cadiz",
  "Cantabria",
  "Castellon",
  "Ceuta",
  "Ciudad Real",
  "Cordoba",
  "Cuenca",
  "Girona",
  "Granada",
  "Guadalajara",
  "Guipuzcoa",
  "Huelva",
  "Huesca",
  "Illes Balears",
  "Jaen",
  "La Rioja",
  "Las Palmas",
  "Leon",
  "Lleida",
  "Lugo",
  "Madrid",
  "Malaga",
  "Melilla",
  "Murcia",
  "Navarra",
  "Ourense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Vizcaya",
  "Zamora",
  "Zaragoza",
]

export const zapatillasData: Record<string, Product[]> = {
  Dior: [
    {
      id: "dior-b22",
      slug: "dior-b22",
      name: "Dior B22",
      brand: "Dior",
      description:
        "Zapatillas B22: diseño chunky y elegante con materiales premium transpirables para máxima comodidad diaria. Disponibles en negro y gris o blanco. Alta calidad garantizada, incluye caja original Dior. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Disponible de nuevo - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso en casa. ¡Estilo de lujo al alcance!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b22%20color%20negro-J4F5HyKAYxIgYOW7LEXhL0GfoDKgA8.jpg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b22%20color%20negro-J4F5HyKAYxIgYOW7LEXhL0GfoDKgA8.jpg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/video%20dior%20b22%20color%20negro%20y%20gris-9ql87fyaTsnnwIeLVi7ZYYln7XLU2U.mp4",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/video%20dior%20b22%20color%20blanco-Y0xYnZm7rGZXwNYewFlNuWQ2CsWVNP.mp4",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro-Gris", "Blanco", "Negro"],
    },
    {
      id: "dior-b30",
      slug: "dior-b30",
      name: "Dior B30",
      brand: "Dior",
      description:
        "Zapatillas Dior B30: silueta moderna y versátil, perfectas para looks urbanos con malla resistente y suela acolchada. Nuevo color negro y blanco disponible. Alta calidad garantizada, incluye caja original Dior como en la foto. Tallas: 40, 41, 42, 43, 44, 45. Precio: 65€ (¡Color top ventas - Oferta SAVE 35% de 100€!). Envío en 24-48 horas, pago seguro en casa.",
      price: 65,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b30%20color%20blanco-SEFPcA2TFFrMTN4mfhRkpHWYHWmBzC.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b30%20color%20blanco-SEFPcA2TFFrMTN4mfhRkpHWYHWmBzC.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/video%20b30%20color%20blanco%20y%20negro-2Bg4e4Ghk678MOyAM2LqjPTTofjXGd.mp4",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco", "Negro y Blanco"],
    },
  ],
  "New Balance": [
    {
      id: "nb-9060-negro",
      slug: "nb-9060-negro",
      name: "New Balance 9060 Negro",
      brand: "New Balance",
      description:
        "New Balance 9060 en negro: equilibrio perfecto entre retro y moderno, con amortiguación superior para todo el día. Alta calidad garantizada, incluye caja original New Balance y accesorios. Tallas disponibles: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Bestseller - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡No te quedes sin ellas!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20negro-zCPARnnaRzXtQaHoDQJxEewHmbOSWQ.png",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20negro-zCPARnnaRzXtQaHoDQJxEewHmbOSWQ.png",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20negro%202-n279pnX4WEvORCCNZiDkPEYF8ZoRQC.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "nb-9060-blanco",
      slug: "nb-9060-blanco",
      name: "New Balance 9060 Blanco",
      brand: "New Balance",
      description:
        "New Balance 9060 en blanco: diseño fresco y versátil con amortiguación avanzada para confort todo el día. Alta calidad garantizada, incluye caja original New Balance y accesorios. Tallas disponibles: 36, 37, 38, 39, 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Novedad - SAVE 30% de 100€!). Envío en 24-48 horas, pago en casa. ¡Estilo impecable!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20blancas-Bh8Dgr1fVr7MSmhaw8Z4L4fqrHI6rB.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20blancas-Bh8Dgr1fVr7MSmhaw8Z4L4fqrHI6rB.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20blancas%202-tCeLMHIG9SehLXWEwJDViAur4rThKM.jpeg",
      ],
      sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
      colors: ["Blanco"],
    },
    {
      id: "nb-9060-rosa",
      slug: "nb-9060-rosa",
      name: "New Balance 9060 Rosa",
      brand: "New Balance",
      description:
        "New Balance 9060: equilibrio perfecto entre retro y moderno, con amortiguación superior para todo el día. Nuevo color rosa disponible. Alta calidad garantizada, incluye caja original New Balance y accesorios. Tallas: 36, 37, 38, 39, 40. Precio: 70€ (¡Novedad femenina - SAVE 30% de 100€!). Envío en 24-48 horas, pago en casa. ¡Estilo vibrante!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20rosa-wfkGfBWuoYmEhHmdpJ2s25xz8c38Jq.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20rosa-wfkGfBWuoYmEhHmdpJ2s25xz8c38Jq.jpeg",
      ],
      sizes: ["36", "37", "38", "39", "40"],
      colors: ["Rosa"],
    },
    {
      id: "nb-2000-rosa",
      slug: "nb-2000-rosa",
      name: "New Balance 2000 Rosa",
      brand: "New Balance",
      description:
        "New Balance 2000: diseño clásico con amortiguación superior para rendimiento diario. Alta calidad garantizada. Tallas: 36, 37, 38, 39, 40. Precio: 40€ (¡Oferta económica - SAVE 33% de 60€!). Envío en 24-48 horas, pago contra reembolso en casa. ¡Calidad accesible!",
      price: 40,
      originalPrice: 60,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/New%20balance%202000-VfJnkbdEVwZobnaebVE8erYOFRU6yf.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/New%20balance%202000-VfJnkbdEVwZobnaebVE8erYOFRU6yf.jpeg",
      ],
      sizes: ["36", "37", "38", "39", "40"],
      colors: ["Rosa"],
    },
  ],
  Nike: [
    {
      id: "nike-react",
      slug: "nike-react",
      name: "Nike React",
      brand: "Nike",
      description:
        "Nike React: tecnología de espuma reactiva para rebote y comodidad extrema en cada paso. Disponibles en 4 colores vibrantes: gris puro, negro elegante, gris-marrón urbano y gris-negro mix. Alta calidad garantizada, incluye caja original Nike. Tallas: 40, 41, 42, 43, 44, 45. Precio: 65€ (¡Oferta flash - SAVE 35% de 100€!). Envío en 24-48 horas, pago en casa sin riesgos.",
      price: 65,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20gris-SnGGN2vWSRCqzcpf2QoRVTugl7dOuj.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20gris-SnGGN2vWSRCqzcpf2QoRVTugl7dOuj.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20negro-ihh69OKtXlAYOoMNoAh98NHu4Sdi7d.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20marr%C3%B3n%20y%20gris-WkHWWeEeJM0THOIFFTwU4lTkP2rv17.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20gris%20y%20negro-LC0fmaVc79GS7tRiFdufWgakQqptgz.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Gris", "Negro", "Gris-Marrón", "Gris-Negro"],
    },
    {
      id: "nike-shox-negro",
      slug: "nike-shox-negro",
      name: "Nike Shox Negro",
      brand: "Nike",
      description:
        "Nike Shox en negro: sistema de amortiguación Shox para energía explosiva y comodidad innovadora. Perfectas para atletas o looks diarios. Alta calidad garantizada, incluye caja original Nike. Tallas: 36, 37, 38, 39, 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Oferta limitada - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso.",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20shox%20negra-yfcWSuuHSmzOSWKjfUJuhnuopQ2ZbD.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20shox%20negra-yfcWSuuHSmzOSWKjfUJuhnuopQ2ZbD.jpeg",
      ],
      sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "nike-airmax95-cortez-negro",
      slug: "nike-airmax95-cortez-negro",
      name: "Air Max 95 x Cortez Negro",
      brand: "Nike",
      description:
        "Zapatillas Air Max 95 x Cortez en negro: fusión icónica con amortiguación Air y detalles amarillos para comodidad diaria. Alta calidad garantizada. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Colaboración exclusiva - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Eleva tu paso!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Air%20max%2095%20x%20cortez%20color%20negro%202-upKF6t1BhqZMiIeHK8zKU0981xXxVE.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Air%20max%2095%20x%20cortez%20color%20negro%202-upKF6t1BhqZMiIeHK8zKU0981xXxVE.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/video%20Air%20max%2095%20x%20cortez%20color%20negro-T7fjxIsHCzK17mHtjR4Ul5ujv972uU.mp4",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "nike-shox-camaleon",
      slug: "nike-shox-camaleon",
      name: "Nike Shox Camaleón",
      brand: "Nike",
      description:
        "Shox Camaleón: sistema de amortiguación Shox para energía explosiva y comodidad innovadora. Disponibles en 3 colores: azul, rojo y verde. Alta calidad garantizada, incluye caja original y todo. Precio: 70€ (¡Oferta versátil - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu color!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20shox%20camaleon-yt0aBPlRiEplt3E02lCtXMVsgu7MNF.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20shox%20camaleon-yt0aBPlRiEplt3E02lCtXMVsgu7MNF.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Azul", "Rojo", "Verde"],
    },
    {
      id: "nike-af1-nocta",
      slug: "nike-af1-nocta",
      name: "Air Force 1 x Nocta Blanco",
      brand: "Nike",
      description:
        "Air Force 1 x Nocta: fusión clásica con detalles premium, doble cordones y suela resistente. Alta calidad garantizada, increíble acabado. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Colaboración exclusiva - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Eleva tu estilo!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/air%20force%20x%20nocta%20color%20blanco-zdMc0rQRb7SF6Vj4qsKpRBUjkCe6eP.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/air%20force%20x%20nocta%20color%20blanco-zdMc0rQRb7SF6Vj4qsKpRBUjkCe6eP.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco"],
    },
  ],
  Asics: [
    {
      id: "asics-gel-negro",
      slug: "asics-gel-negro",
      name: "Asics Gel Negro",
      brand: "Asics",
      description:
        "Asics Gel en negro: amortiguación Gel icónica para absorción de impactos y rendimiento superior. Diseño sleek para running o casual. Alta calidad garantizada, incluye caja original Asics. Tallas: 40, 41, 42, 43, 44, 45. Precio: 65€ (¡Últimas unidades - SAVE 35% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Calidad que dura!",
      price: 65,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/asic%20gel%20negro-SqV5WVNGiZfS1OpzhsGrlPOqA1HqFE.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/asic%20gel%20negro-SqV5WVNGiZfS1OpzhsGrlPOqA1HqFE.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
  ],
  Amiri: [
    {
      id: "amiri-sneakers",
      slug: "amiri-sneakers",
      name: "Zapatillas Amiri",
      brand: "Amiri",
      description:
        "Zapatillas Amiri: estilo streetwear de lujo con detalles premium y suela resistente. Alta calidad garantizada, incluye caja original Amiri. Tallas disponibles: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Exclusivo - SAVE 30% de 100€!). Envío en 24-48 horas, pago seguro en casa. ¡Eleva tu outfit!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri-KkZLd5lJWqZ8u3mEmrebMeGeKhZupu.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri-KkZLd5lJWqZ8u3mEmrebMeGeKhZupu.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri%202-PfdqE3Qj0gXauxd6m3eonQFBQA9AA5.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri%203-Zf90zJEZq9CQKiUMHkC1ixe2Kf12qb.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri%204-STCP7aKibmDYAOMOMdHqWzc5A9Z0pv.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro/Blanco"],
    },
  ],
  Nocta: [
    {
      id: "nocta-glide-negro",
      slug: "nocta-glide-negro",
      name: "Nike Nocta Glide Negro",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en negra: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Clásico - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nike%20nocta%20glide%20color%20negro-MpyO38ZV8Q2ZIuuOVo7nadLa8z1waG.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nike%20nocta%20glide%20color%20negro-MpyO38ZV8Q2ZIuuOVo7nadLa8z1waG.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "nocta-glide-negro-rojo",
      slug: "nocta-glide-negro-rojo",
      name: "Nike Nocta Glide Negro y Rojo",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en negro y rojo: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Versátil - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nike%20nocta%20glide%20color%20negro%20y%20rojo-ZCg4SUNq1eG1MSF4TtFvRmcMiSJUp6.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nike%20nocta%20glide%20color%20negro%20y%20rojo-ZCg4SUNq1eG1MSF4TtFvRmcMiSJUp6.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro-Rojo"],
    },
    {
      id: "nocta-glide-blanca",
      slug: "nocta-glide-blanca",
      name: "Nike Nocta Glide Blanca",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en blanca: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Fresco - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20blanco-u42TsleumFjwRsnTLO8jAmYGeR1HGV.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20blanco-u42TsleumFjwRsnTLO8jAmYGeR1HGV.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco"],
    },
    {
      id: "nocta-glide-negro-blanco",
      slug: "nocta-glide-negro-blanco",
      name: "Nike Nocta Glide Negro y Blanco",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en negro y blanco: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Contraste - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20negro%20y%20blanco-Ae7SqDHxe567NruJt6SKBZsPHFEZGe.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20negro%20y%20blanco-Ae7SqDHxe567NruJt6SKBZsPHFEZGe.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro-Blanco"],
    },
    {
      id: "nocta-glide-negro-dorado",
      slug: "nocta-glide-negro-dorado",
      name: "Nike Nocta Glide Negro y Dorado",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en negro y dorado: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Lujoso - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20negro%20y%20dorado-0T5iN9x9t4nKKy3eGiQRupv6PyIlnh.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20negro%20y%20dorado-0T5iN9x9t4nKKy3eGiQRupv6PyIlnh.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro-Dorado"],
    },
    {
      id: "nocta-glide-roja",
      slug: "nocta-glide-roja",
      name: "Nike Nocta Glide Roja",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en roja: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Vibrante - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20rojo-UlF6UiZLIKphMWveGVHfgtiT8OCdh5.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20rojo-UlF6UiZLIKphMWveGVHfgtiT8OCdh5.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Rojo"],
    },
    {
      id: "nocta-glide-blanco-negro",
      slug: "nocta-glide-blanco-negro",
      name: "Nike Nocta Glide Blanco y Negro",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en blanco y negro: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Dual - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20blanco%20y%20negro-Cm1ZmeR4PPlo7w5u4o0fmSzunqIdjb.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20blanco%20y%20negro-Cm1ZmeR4PPlo7w5u4o0fmSzunqIdjb.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco-Negro"],
    },
    {
      id: "nocta-glide-negro-2",
      slug: "nocta-glide-negro-2",
      name: "Nike Nocta Glide Negro 2",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en negro variante 2: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Clásico alternativo - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20negro%202-LUwTy0ESEVJZwLVIBYJKDtBZCnsrFe.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20negro%202-LUwTy0ESEVJZwLVIBYJKDtBZCnsrFe.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "nocta-glide-naranja",
      slug: "nocta-glide-naranja",
      name: "Nike Nocta Glide Naranja",
      brand: "Nocta",
      description:
        "Nike Nocta Glide en naranja: diseño urbano con amortiguación superior y detalles premium. Alta calidad garantizada, incluye caja Nike roja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Energético - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo innovador!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20naranja-8qsuB2DlCpZH9PiAQ7NLWe9rQJfn2g.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20nocta%20glide%20color%20naranja-8qsuB2DlCpZH9PiAQ7NLWe9rQJfn2g.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Naranja"],
    },
  ],
  "Louis Vuitton": [
    {
      id: "lv-trainer",
      slug: "lv-trainer",
      name: "LV Trainer",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Trainer: diseño icónico con detalles premium y suela cómoda para uso versátil. Disponibles en blanco-azul fresco o blanco-negro elegante. Alta calidad garantizada, incluye caja original LV. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Oferta limitada - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso en casa. ¡Estilo premium accesible!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lv%20trainer%20color%20blanco%20y%20negro-Myw9S4x6Hpc0OtwLVLiqpFIhnE6oyH.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lv%20trainer%20color%20blanco%20y%20negro-Myw9S4x6Hpc0OtwLVLiqpFIhnE6oyH.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lv%20trainer%20color%20azul-6RQJC8cGh3YuKNv2vooECIoxHGYtlg.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco-Negro", "Blanco-Azul"],
    },
    {
      id: "lv-trainer-negro",
      slug: "lv-trainer-negro",
      name: "LV Trainer Negro",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Trainer en negro: diseño icónico con detalles premium y suela cómoda para uso versátil. Alta calidad garantizada, incluye caja original LV. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Novedad - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso en casa. ¡Estilo premium accesible!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20trainer%20color%20negro%20nuevas-fEvToBcN8JLKvyHtZ2SHYCmflvI6Ej.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20trainer%20color%20negro%20nuevas-fEvToBcN8JLKvyHtZ2SHYCmflvI6Ej.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "lv-skate-piedras",
      slug: "lv-skate-piedras",
      name: "LV Skate Piedras Brillantes",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Skate nuevas con piedras brillantes: estilo lujoso y llamativo con detalles cristalinos y suela premium. Nuevos colores negro y negro-gris disponibles. Alta calidad garantizada, incluye caja original LV naranja. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Edición limitada - SAVE 30% de 100€!). Envío en 24-48 horas, pago seguro en casa. ¡Brilla con estilo!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20nuevas%20de%20piedras%20brillantes%20color%20crema-jzAcUE58h2dRQ5PlEtrucTVztLvuGs.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20nuevas%20de%20piedras%20brillantes%20color%20crema-jzAcUE58h2dRQ5PlEtrucTVztLvuGs.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20nuevas%20de%20piedras%20brillantes%20color%20azul-xBIO14dZmeyRMDYwnFkWPTFRFwG9zB.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20nuevas%20de%20piedras%20brillantes%20color%20negro%20y%20gris-b8Q1O4MnEz40VpIjmu6GeZoDyNykQ2.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20nuevas%20de%20piedras%20brillantes%20color%20negro-pNzfqgQdrAkUgnv40kdwV9zcvnXaGz.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/video%20lv%20skate%20nuevas%20de%20piedras%20brillantes%20blanco%20y%20gris-iDsnTlXewPbQ4VyEyOoFhmcqac4ETd.mp4",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro y Gris", "Crema", "Azul", "Blanco y Gris", "Negro"],
    },
    {
      id: "lv-skate-blanco",
      slug: "lv-skate-blanco",
      name: "LV Skate Blanco",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Skate en blanco: estilo lujoso con suela premium para comodidad diaria. Alta calidad garantizada. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Novedad - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Brilla con estilo!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20gris-JU6BjQ9K8DFfgwSnoil1uMv3MYhoZZ.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20gris-JU6BjQ9K8DFfgwSnoil1uMv3MYhoZZ.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco"],
    },
    {
      id: "lv-skate-gris",
      slug: "lv-skate-gris",
      name: "LV Skate Gris",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Skate en gris: diseño versátil con detalles premium. Alta calidad garantizada. Tallas: 40, 41, 42, 43, 44, 45. Precio: 55€ (¡Oferta especial - SAVE 31% de 80€!). Envío en 24-48 horas, pago contra reembolso. ¡Elegancia sutil!",
      price: 55,
      originalPrice: 80,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20blanco-LFoaJ7eJCk1cP2dEfCUmICpHZbkL7Y.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20blanco-LFoaJ7eJCk1cP2dEfCUmICpHZbkL7Y.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Gris"],
    },
    {
      id: "lv-skate-negro",
      slug: "lv-skate-negro",
      name: "LV Skate Negro",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Skate en negro: estilo lujoso con suela premium para uso diario. Alta calidad garantizada. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Clásico - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Potencia tu look!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20negro-Y5KT3w8zuVFgTjMwOceXFVhlSI3wpQ.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20skate%20negro-Y5KT3w8zuVFgTjMwOceXFVhlSI3wpQ.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "lv-skate-blanco-negro",
      slug: "lv-skate-blanco-negro",
      name: "LV Skate Blanco y Negro",
      brand: "Louis Vuitton",
      description:
        "Zapatillas LV Skate en blanco y negro: contraste elegante con detalles premium. Alta calidad garantizada. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Versátil - SAVE 30% de 100€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo dual!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20vuitton%20skate%20blanco%20y%20negro-anOIWhhL9ZxRlZI9tufE7AUWXKKKB4.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lv%20vuitton%20skate%20blanco%20y%20negro-anOIWhhL9ZxRlZI9tufE7AUWXKKKB4.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco y Negro"],
    },
  ],
}

export const accesoriosData: Product[] = [
  {
    id: "bolso-louis-vuitton",
    slug: "bolso-louis-vuitton",
    name: "Bolso Louis Vuitton",
    brand: "Louis Vuitton",
    description:
      "Bolso de mano con cintura Louis Vuitton: diseño elegante y funcional con materiales premium para uso diario. Alta calidad garantizada. Precio: 40€ (¡Oferta accesorio - SAVE 33% de 60€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo práctico de lujo!",
    price: 40,
    originalPrice: 60,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20luis%20vuitton-VlehMyFDKDtpM8dlKeIdFNOneQXHVB.jpeg",
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20luis%20vuitton-VlehMyFDKDtpM8dlKeIdFNOneQXHVB.jpeg",
    ],
  },
  {
    id: "bolso-louis-vuitton-paris",
    slug: "bolso-louis-vuitton-paris",
    name: "Bolso Louis Vuitton Paris",
    brand: "Louis Vuitton",
    description:
      "Bolso de mano con cintura Louis Vuitton Paris: edición especial con toque parisino y materiales premium. Alta calidad garantizada. Precio: 40€ (¡Limitado - SAVE 33% de 60€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo francés accesible!",
    price: 40,
    originalPrice: 60,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20luis%20vuitton%20paris-ocFDsUFcvRSmQzzuIKeNgJjGmS5cgM.jpeg",
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20luis%20vuitton%20paris-ocFDsUFcvRSmQzzuIKeNgJjGmS5cgM.jpeg",
    ],
  },
  {
    id: "bolso-gucci",
    slug: "bolso-gucci",
    name: "Bolso Gucci",
    brand: "Gucci",
    description:
      "Bolso de mano con cintura Gucci: diseño icónico y versátil con detalles premium. Alta calidad garantizada. Precio: 40€ (¡Oferta exclusiva - SAVE 33% de 60€!). Envío en 24-48 horas, pago contra reembolso. ¡Accesorio premium!",
    price: 40,
    originalPrice: 60,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20gucci-a4Xnj9Ly5kDzUbUNVoI9Yc1x3q0XF5.jpeg",
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20gucci-a4Xnj9Ly5kDzUbUNVoI9Yc1x3q0XF5.jpeg",
    ],
  },
  {
    id: "bolso-prada",
    slug: "bolso-prada",
    name: "Bolso Prada",
    brand: "Prada",
    description:
      "Bolso de mano con cintura Prada: estilo minimalista y elegante con materiales resistentes. Alta calidad garantizada. Precio: 40€ (¡Novedad - SAVE 33% de 60€!). Envío en 24-48 horas, pago contra reembolso. ¡Funcional y chic!",
    price: 40,
    originalPrice: 60,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20prada-lFGuiSUMHuW8F3VjXxht6E4xXdjk9F.jpeg",
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20prada-lFGuiSUMHuW8F3VjXxht6E4xXdjk9F.jpeg",
    ],
  },
  {
    id: "bolso-lacoste",
    slug: "bolso-lacoste",
    name: "Bolso Lacoste",
    brand: "Lacoste",
    description:
      "Bolso de mano con cintura Lacoste: diseño deportivo y práctico con logo icónico. Alta calidad garantizada. Precio: 40€ (¡Oferta comfy - SAVE 33% de 60€!). Envío en 24-48 horas, pago contra reembolso. ¡Versátil para el día a día!",
    price: 40,
    originalPrice: 60,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20lacoste-n9qUwjS6bT0MHGn8L38263ee6Snm3Y.jpeg",
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bolso%20lacoste-n9qUwjS6bT0MHGn8L38263ee6Snm3Y.jpeg",
    ],
  },
]

export const ropaData: Record<string, Record<string, Product[]>> = {
  Chandal: {
    Nike: [
      {
        id: "chandal-nike-tech-blanco-gris",
        slug: "chandal-nike-tech-blanco-gris",
        name: "Tech Blanco-Gris",
        brand: "Nike",
        description:
          "Tech: diseño innovador con materiales premium para comodidad y estilo diario. Disponibles en 8 colores. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Multi-color top - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu vibe!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20blanco%20y%20gris-g5j9o6YpSVB1SzqpHrOocvzKtgKtNL.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20blanco%20y%20gris-g5j9o6YpSVB1SzqpHrOocvzKtgKtNL.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blanco-Gris"],
      },
      {
        id: "chandal-nike-tech-blanco-verde",
        slug: "chandal-nike-tech-blanco-verde",
        name: "Tech Blanco-Verde",
        brand: "Nike",
        description:
          "Tech: diseño innovador con materiales premium para comodidad y estilo diario. Disponibles en 6 colores. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Multi-color top - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu vibe!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20blanco%2C%20verde%20y%20negro-VI9qOF0Task0Zmz7ncLac5NWqqsfD6.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20blanco%2C%20verde%20y%20negro-VI9qOF0Task0Zmz7ncLac5NWqqsfD6.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blanco-Verde"],
      },
      {
        id: "chandal-nike-tech-negro",
        slug: "chandal-nike-tech-negro",
        name: "Tech Negro",
        brand: "Nike",
        description:
          "Tech: diseño innovador con materiales premium para comodidad y estilo diario. Disponibles en 8 colores. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Multi-color top - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu vibe!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20negro%2C%20blanco%20y%20gris-xAabefJ4KGujPOgfLUWw1X9jfitFTq.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20negro%2C%20blanco%20y%20gris-xAabefJ4KGujPOgfLUWw1X9jfitFTq.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Negro"],
      },
      {
        id: "chandal-nike-tech-azul-claro-gris",
        slug: "chandal-nike-tech-azul-claro-gris",
        name: "Tech Azul Claro-Gris",
        brand: "Nike",
        description:
          "Tech: diseño innovador con materiales premium para comodidad y estilo diario. Disponibles en 8 colores. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Multi-color top - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu vibe!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20azul%20claro%20y%20gris-6zGEV7HcS5ETIegEhjQz25A2KYqsDI.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20azul%20claro%20y%20gris-6zGEV7HcS5ETIegEhjQz25A2KYqsDI.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Azul Claro-Gris"],
      },
      {
        id: "chandal-nike-tech-azul",
        slug: "chandal-nike-tech-azul",
        name: "Tech Azul",
        brand: "Nike",
        description:
          "Tech: diseño innovador con materiales premium para comodidad y estilo diario. Disponibles en 8 colores. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Multi-color top - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu vibe!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20azul%2C%20blanco%20y%20azul%20claro-FMgDCrtJ6QGe7gjOwB0TgtTXdZJ7NL.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20azul%2C%20blanco%20y%20azul%20claro-FMgDCrtJ6QGe7gjOwB0TgtTXdZJ7NL.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Azul"],
      },
      {
        id: "chandal-nike-tech-negro-blanco",
        slug: "chandal-nike-tech-negro-blanco",
        name: "Tech Negro-Blanco",
        brand: "Nike",
        description:
          "Tech: diseño innovador con materiales premium para comodidad y estilo diario. Disponibles en 8 colores. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Multi-color top - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Elige tu vibe!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20negro%20y%20blanco-1D8onFhfTe1xHOZFychNzu4eUR9ylT.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nike%20tech%20color%20negro%20y%20blanco-1D8onFhfTe1xHOZFychNzu4eUR9ylT.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Negro-Blanco"],
      },
    ],
    Lacoste: [
      {
        id: "chandal-lacoste-azul-oscuro",
        slug: "chandal-lacoste-azul-oscuro",
        name: "Chándal Lacoste Azul Oscuro",
        brand: "Lacoste",
        description:
          "Chándal Lacoste: conjunto cómodo y elegante con tela premium para looks casual o deportivos. Nuevo color azul oscuro disponible. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Oferta comfy - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso en casa. ¡Versátil y premium!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20color%20azul%20oscuro-LIDmOFE3GPgjXL0ck8Ka7eOcad8Gdh.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20color%20azul%20oscuro-LIDmOFE3GPgjXL0ck8Ka7eOcad8Gdh.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Azul Oscuro"],
      },
      {
        id: "chandal-lacoste-azul-claro",
        slug: "chandal-lacoste-azul-claro",
        name: "Chándal Lacoste Azul Claro",
        brand: "Lacoste",
        description:
          "Chándal Lacoste: conjunto cómodo y elegante con tela premium para looks casual o deportivos. Color azul claro disponible. Alta calidad garantizada. Tallas: S, M, L, XL. Precio: 60€ (¡Oferta comfy - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso en casa. ¡Versátil y premium!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20color%20azul%20%20claro-gNziDgpzCZgzau0EbPsPthEEFuZwqr.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20color%20azul%20%20claro-gNziDgpzCZgzau0EbPsPthEEFuZwqr.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Azul Claro"],
      },
      {
        id: "chandal-lacoste-cocodrilo-azul",
        slug: "chandal-lacoste-cocodrilo-azul",
        name: "Chándal Lacoste Cocodrilo Azul",
        brand: "Lacoste",
        description:
          "Chándal Lacoste de cocodrilo en azul: conjunto cómodo con logo icónico para looks casual o deportivos. Alta calidad garantizada. Tallas: S, M, L, XL (recomienda una talla más). Precio: 60€ (¡Oferta comfy - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Versátil y premium!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20de%20cocodrilo%20azul-CajxGJBWTlu47IsBqVkGckbKJZ6HyX.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20de%20cocodrilo%20azul-CajxGJBWTlu47IsBqVkGckbKJZ6HyX.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Azul"],
      },
      {
        id: "chandal-lacoste-cocodrilo-blanco-azul",
        slug: "chandal-lacoste-cocodrilo-blanco-azul",
        name: "Chándal Lacoste Cocodrilo Blanco-Azul",
        brand: "Lacoste",
        description:
          "Chándal Lacoste de cocodrilo en blanco y azul: conjunto elegante con logo icónico. Alta calidad garantizada. Tallas: S, M, L, XL (recomienda una talla más). Precio: 60€ (¡Novedad - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Estilo fresco!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20de%20cocodrilo%20blanco%20y%20azul-CcyMkBQ7JF5MyGmAQQrYeFOeWe6ATc.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20de%20cocodrilo%20blanco%20y%20azul-CcyMkBQ7JF5MyGmAQQrYeFOeWe6ATc.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blanco-Azul"],
      },
      {
        id: "chandal-lacoste-2026-azul",
        slug: "chandal-lacoste-2026-azul",
        name: "Chándal Lacoste 2026 Azul",
        brand: "Lacoste",
        description:
          "Chándal Lacoste Nuevo 2026 en azul: diseño actualizado con tela premium, disponible en mucha cantidad. Alta calidad garantizada, muy buenos en venta. Tallas: S, M, L, XL. Precio: 60€ (¡Top ventas - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Increíble calidad!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%202026%20azul-nzjoNGpwvLaxqpU7RdRwNal91zbbtZ.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%202026%20azul-nzjoNGpwvLaxqpU7RdRwNal91zbbtZ.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Azul"],
      },
      {
        id: "chandal-lacoste-2026-marron",
        slug: "chandal-lacoste-2026-marron",
        name: "Chándal Lacoste 2026 Marrón",
        brand: "Lacoste",
        description:
          "Chándal Lacoste Nuevo 2026 en marrón: diseño actualizado con tela premium, disponible en mucha cantidad. Alta calidad garantizada, muy buenos en venta. Tallas: S, M, L, XL. Precio: 60€ (¡Novedad - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Increíble calidad!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nuevo%20lacoste%20marr%C3%B3n-uh0B7cNsmpZyjMXreJKymjOm9VxqJB.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20nuevo%20lacoste%20marr%C3%B3n-uh0B7cNsmpZyjMXreJKymjOm9VxqJB.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Marrón"],
      },
      {
        id: "chandal-lacoste-2026-negro",
        slug: "chandal-lacoste-2026-negro",
        name: "Chándal Lacoste 2026 Negro",
        brand: "Lacoste",
        description:
          "Chándal Lacoste Nuevo 2026 en negro: diseño actualizado con tela premium, disponible en mucha cantidad. Alta calidad garantizada, muy buenos en venta. Tallas: S, M, L, XL. Precio: 60€ (¡Clásico - SAVE 33% de 90€!). Envío en 24-48 horas, pago contra reembolso. ¡Increíble calidad!",
        price: 60,
        originalPrice: 90,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20nuevo%20negro-zvnZPGrCaPOoCgsIrGsRbl0gFzknwY.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20lacoste%20nuevo%20negro-zvnZPGrCaPOoCgsIrGsRbl0gFzknwY.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Negro"],
      },
    ],
    Armani: [
      {
        id: "chandal-armani-negro",
        slug: "chandal-armani-negro",
        name: "Chándal Armani Negro",
        brand: "Armani",
        description:
          "Chándal Armani en negro: conjunto cómodo y elegante con tela premium para looks casual o deportivos. Alta calidad garantizada, vienen pequeños—recomienda una talla más. Tallas: S, M, L, XL. Precio: 55€ (¡Oferta comfy - SAVE 31% de 80€!). Envío en 24-48 horas, pago contra reembolso. ¡Versátil y premium!",
        price: 55,
        originalPrice: 80,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20armani%20azul-hufEaODlXWqg8t1Epm6ITnUICipGWT.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20armani%20azul-hufEaODlXWqg8t1Epm6ITnUICipGWT.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Negro"],
      },
      {
        id: "chandal-armani-blanco",
        slug: "chandal-armani-blanco",
        name: "Chándal Armani Blanco",
        brand: "Armani",
        description:
          "Chándal Armani en blanco: conjunto cómodo y elegante con tela premium para looks casual o deportivos. Alta calidad garantizada, vienen pequeños—recomienda una talla más. Tallas: S, M, L, XL. Precio: 55€ (¡Oferta fresca - SAVE 31% de 80€!). Envío en 24-48 horas, pago contra reembolso. ¡Versátil y premium!",
        price: 55,
        originalPrice: 80,
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20armani%20blanco%20y%20azul-2Cpk80ka7hQKgIEWhaCQPTaETYQQJ2.jpeg",
        images: [
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chandal%20armani%20blanco%20y%20azul-2Cpk80ka7hQKgIEWhaCQPTaETYQQJ2.jpeg",
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blanco"],
      },
    ],
  },
}

export const relojesData: Product[] = [
  {
    id: "reloj-submariner",
    name: "Reloj Submariner Style",
    description: "Reloj inspirado en el Submariner. Acero inoxidable con bisel giratorio.",
    price: 45,
    originalPrice: 80,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-daytona",
    name: "Reloj Daytona Style",
    description: "Cronografo inspirado en el Daytona. Esfera negra con subdiales.",
    price: 50,
    originalPrice: 85,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-datejust",
    name: "Reloj DateJust Style",
    description: "Reloj clasico con calendario. Correa metalica jubilee.",
    price: 42,
    originalPrice: 75,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-royal-oak",
    name: "Reloj Royal Oak Style",
    description: "Inspirado en el iconico Royal Oak. Bisel octogonal en acero.",
    price: 55,
    originalPrice: 95,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-nautilus",
    name: "Reloj Nautilus Style",
    description: "Diseno inspirado en el Nautilus. Esfera azul con textura horizontal.",
    price: 52,
    originalPrice: 90,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-santos",
    name: "Reloj Santos Style",
    description: "Reloj cuadrado inspirado en el Santos. Elegancia atemporal.",
    price: 48,
    originalPrice: 82,
    image: "/images/reloj-luxury.jpg",
  },
]

export const perfumesData: Product[] = [
  {
    id: "perfume-bleu",
    name: "Eau de Parfum Blue Intense",
    description: "Fragancia masculina amaderada con notas citricas. Inspirado en Chanel Bleu.",
    price: 28,
    originalPrice: 50,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-sauvage",
    name: "Sauvage Style EDT",
    description: "Fragancia fresca y especiada. Inspirado en Dior Sauvage.",
    price: 30,
    originalPrice: 55,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-good-girl",
    name: "Good Girl Style",
    description: "Fragancia femenina sensual con notas de jazmin y cacao.",
    price: 28,
    originalPrice: 48,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-one-million",
    name: "One Million Style",
    description: "Fragancia masculina dulce y especiada. Irresistible.",
    price: 25,
    originalPrice: 45,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-coco",
    name: "Coco Mademoiselle Style",
    description: "Fragancia femenina fresca y oriental. Elegancia parisina.",
    price: 32,
    originalPrice: 55,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-acqua",
    name: "Acqua Di Gio Style",
    description: "Fragancia acuatica y fresca. Perfecta para el dia a dia.",
    price: 26,
    originalPrice: 48,
    image: "/images/perfume-luxury.jpg",
  },
]
