import { Product } from "./types"

export const PROVINCIAS_ESPANA = [
  "A Coruna",
  "Alava",
  "Albacete",
  "Alicante",
  "Almeria",
  "Asturias",
  "Avila",
  "Badajoz",
  "Barcelona",
  "Burgos",
  "Caceres",
  "Cadiz",
  "Cantabria",
  "Castellon",
  "Ceuta",
  "Ciudad Real",
  "Cordoba",
  "Cuenca",
  "Girona",
  "Granada",
  "Guadalajara",
  "Guipuzcoa",
  "Huelva",
  "Huesca",
  "Illes Balears",
  "Jaen",
  "La Rioja",
  "Las Palmas",
  "Leon",
  "Lleida",
  "Lugo",
  "Madrid",
  "Malaga",
  "Melilla",
  "Murcia",
  "Navarra",
  "Ourense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Vizcaya",
  "Zamora",
  "Zaragoza",
]

export const zapatillasData: Record<string, Product[]> = {
  Dior: [
    {
      id: "dior-b22",
      slug: "dior-b22",
      name: "Dior B22",
      brand: "Dior",
      description:
        "Zapatillas Dior B22: diseño chunky y elegante con materiales premium transpirables para máxima comodidad diaria. Alta calidad garantizada, incluye caja original Dior. Tallas disponibles: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Oferta limitada - SAVE 30% de 100€!). Envío gratis en 2-3 días, pago contra reembolso en casa. ¡Estilo de lujo al alcance!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b22%20color%20negro-J4F5HyKAYxIgYOW7LEXhL0GfoDKgA8.jpg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b22%20color%20negro-J4F5HyKAYxIgYOW7LEXhL0GfoDKgA8.jpg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "dior-b30",
      slug: "dior-b30",
      name: "Dior B30",
      brand: "Dior",
      description:
        "Zapatillas Dior B30: silueta moderna y versátil, perfectas para looks urbanos con malla resistente y suela acolchada. Disponibles en negro clásico o blanco fresco. Alta calidad garantizada, incluye caja original Dior. Tallas: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Stock bajo - Oferta SAVE 30% de 100€!). Envío gratis 2-3 días, pago seguro en casa.",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b30%20color%20blanco-SEFPcA2TFFrMTN4mfhRkpHWYHWmBzC.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b30%20color%20blanco-SEFPcA2TFFrMTN4mfhRkpHWYHWmBzC.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dior%20b22%20color%20negro-J4F5HyKAYxIgYOW7LEXhL0GfoDKgA8.jpg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Blanco", "Negro"],
    },
  ],
  "New Balance": [
    {
      id: "nb-9060-negro",
      slug: "nb-9060-negro",
      name: "New Balance 9060 Negro",
      brand: "New Balance",
      description:
        "New Balance 9060 en negro: equilibrio perfecto entre retro y moderno, con amortiguación superior para todo el día. Alta calidad garantizada, incluye caja original New Balance y accesorios. Tallas disponibles: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Bestseller - SAVE 30% de 100€!). Envío gratis en 2-3 días, pago contra reembolso. ¡No te quedes sin ellas!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20negro-zCPARnnaRzXtQaHoDQJxEewHmbOSWQ.png",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20negro-zCPARnnaRzXtQaHoDQJxEewHmbOSWQ.png",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20color%20negro%202-n279pnX4WEvORCCNZiDkPEYF8ZoRQC.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
    {
      id: "nb-9060-blanco",
      slug: "nb-9060-blanco",
      name: "New Balance 9060 Blanco",
      brand: "New Balance",
      description:
        "New Balance 9060 en blanco: diseño fresco y versátil con amortiguación avanzada para confort todo el día. Alta calidad garantizada, incluye caja original New Balance y accesorios. Tallas disponibles: 36, 37, 38, 39, 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Novedad - SAVE 30% de 100€!). Envío gratis 2-3 días, pago en casa. ¡Estilo impecable!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20blancas-Bh8Dgr1fVr7MSmhaw8Z4L4fqrHI6rB.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20blancas-Bh8Dgr1fVr7MSmhaw8Z4L4fqrHI6rB.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new%20balance%209060%20blancas%202-tCeLMHIG9SehLXWEwJDViAur4rThKM.jpeg",
      ],
      sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
      colors: ["Blanco"],
    },
  ],
  Nike: [
    {
      id: "nike-react",
      slug: "nike-react",
      name: "Nike React",
      brand: "Nike",
      description:
        "Nike React: tecnología de espuma reactiva para rebote y comodidad extrema en cada paso. Disponibles en 4 colores vibrantes: gris puro, negro elegante, gris-marrón urbano y gris-negro mix. Alta calidad garantizada, incluye caja original Nike. Tallas: 40, 41, 42, 43, 44, 45. Precio: 65€ (¡Oferta flash - SAVE 35% de 100€!). Envío gratis 2-3 días, pago en casa sin riesgos.",
      price: 65,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20gris-SnGGN2vWSRCqzcpf2QoRVTugl7dOuj.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20gris-SnGGN2vWSRCqzcpf2QoRVTugl7dOuj.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20negro-ihh69OKtXlAYOoMNoAh98NHu4Sdi7d.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20react%20marr%C3%B3n%20y%20gris-WkHWWeEeJM0THOIFFTwU4lTkP2rv17.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Gris", "Negro", "Gris-Marrón", "Gris-Negro"],
    },
    {
      id: "nike-shox-negro",
      slug: "nike-shox-negro",
      name: "Nike Shox Negro",
      brand: "Nike",
      description:
        "Nike Shox en negro: sistema de amortiguación Shox para energía explosiva y comodidad innovadora. Perfectas para atletas o looks diarios. Alta calidad garantizada, incluye caja original Nike. Tallas: 36, 37, 38, 39, 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Oferta limitada - SAVE 30% de 100€!). Envío gratis en 2-3 días, pago contra reembolso.",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20shox%20negra-yfcWSuuHSmzOSWKjfUJuhnuopQ2ZbD.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/nike%20shox%20negra-yfcWSuuHSmzOSWKjfUJuhnuopQ2ZbD.jpeg",
      ],
      sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
  ],
  Asics: [
    {
      id: "asics-gel-negro",
      slug: "asics-gel-negro",
      name: "Asics Gel Negro",
      brand: "Asics",
      description:
        "Asics Gel en negro: amortiguación Gel icónica para absorción de impactos y rendimiento superior. Diseño sleek para running o casual. Alta calidad garantizada, incluye caja original Asics. Tallas: 40, 41, 42, 43, 44, 45. Precio: 65€ (¡Últimas unidades - SAVE 35% de 100€!). Envío gratis en 2-3 días, pago contra reembolso. ¡Calidad que dura!",
      price: 65,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/asic%20gel%20negro-SqV5WVNGiZfS1OpzhsGrlPOqA1HqFE.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/asic%20gel%20negro-SqV5WVNGiZfS1OpzhsGrlPOqA1HqFE.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro"],
    },
  ],
  Amiri: [
    {
      id: "amiri-sneakers",
      slug: "amiri-sneakers",
      name: "Zapatillas Amiri",
      brand: "Amiri",
      description:
        "Zapatillas Amiri: estilo streetwear de lujo con detalles premium y suela resistente. Alta calidad garantizada, incluye caja original Amiri. Tallas disponibles: 40, 41, 42, 43, 44, 45. Precio: 70€ (¡Exclusivo - SAVE 30% de 100€!). Envío gratis 2-3 días, pago seguro en casa. ¡Eleva tu outfit!",
      price: 70,
      originalPrice: 100,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri-KkZLd5lJWqZ8u3mEmrebMeGeKhZupu.jpeg",
      images: [
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri-KkZLd5lJWqZ8u3mEmrebMeGeKhZupu.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri%202-PfdqE3Qj0gXauxd6m3eonQFBQA9AA5.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri%203-Zf90zJEZq9CQKiUMHkC1ixe2Kf12qb.jpeg",
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/amiri%204-STCP7aKibmDYAOMOMdHqWzc5A9Z0pv.jpeg",
      ],
      sizes: ["40", "41", "42", "43", "44", "45"],
      colors: ["Negro/Blanco"],
    },
  ],
}

export const accesoriosData: Product[] = [
  {
    id: "gorra-premium-1",
    name: "Gorra Snapback Premium",
    description: "Gorra ajustable con bordado de alta calidad. Material resistente y comodo.",
    price: 18,
    originalPrice: 30,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "gorra-dad-hat",
    name: "Dad Hat Classic",
    description: "Gorra estilo dad hat con cierre de hebilla metalica. Look casual elegante.",
    price: 15,
    originalPrice: 25,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "bolso-crossbody",
    name: "Bolso Crossbody Urban",
    description: "Bolso cruzado inspirado en marcas de lujo. Perfecto para el dia a dia.",
    price: 35,
    originalPrice: 60,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "bolso-tote",
    name: "Tote Bag Premium",
    description: "Bolso tote de gran capacidad con acabados de alta calidad.",
    price: 40,
    originalPrice: 70,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "cinturon-lujo",
    name: "Cinturon Piel Premium",
    description: "Cinturon de piel sintetica con hebilla metalica grabada.",
    price: 22,
    originalPrice: 38,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "gafas-sol",
    name: "Gafas de Sol Aviator",
    description: "Gafas de sol estilo aviador con proteccion UV400. Marco metalico.",
    price: 20,
    originalPrice: 35,
    image: "/images/accesorio-gorra.jpg",
  },
]

export const ropaData: Record<string, Record<string, Product[]>> = {
  Chandal: {
    Nike: [
      {
        id: "chandal-nike-1",
        name: "Chandal Deportivo Negro",
        description: "Chandal completo (chaqueta + pantalon) en negro. Tejido transpirable.",
        price: 55,
        originalPrice: 90,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
      {
        id: "chandal-nike-2",
        name: "Chandal Tech Fleece",
        description: "Chandal de forro polar tecnico. Ligero y abrigado.",
        price: 65,
        originalPrice: 110,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
    "Louis Vuitton": [
      {
        id: "chandal-lv-1",
        name: "Chandal Monogram",
        description: "Chandal inspirado en la linea monogram. Acabados premium.",
        price: 70,
        originalPrice: 120,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
    Adidas: [
      {
        id: "chandal-adidas-1",
        name: "Chandal 3 Rayas Classic",
        description: "El clasico chandal con las tres rayas iconicas.",
        price: 50,
        originalPrice: 85,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
  },
  Chaqueta: {
    Nike: [
      {
        id: "chaqueta-nike-1",
        name: "Windrunner Jacket",
        description: "Chaqueta cortavientos ligera y resistente al agua.",
        price: 45,
        originalPrice: 75,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
    "The North Face": [
      {
        id: "chaqueta-tnf-1",
        name: "Puffer Jacket 700",
        description: "Chaqueta acolchada inspirada en el modelo 700. Abrigada y estilosa.",
        price: 60,
        originalPrice: 100,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
  },
  Camiseta: {
    Nike: [
      {
        id: "camiseta-nike-1",
        name: "Camiseta Essential Swoosh",
        description: "Camiseta basica de algodon con logo bordado.",
        price: 18,
        originalPrice: 30,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
    "Louis Vuitton": [
      {
        id: "camiseta-lv-1",
        name: "Camiseta Logo Estampado",
        description: "Camiseta premium con estampado de logo. Algodon 100%.",
        price: 28,
        originalPrice: 45,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
    Gucci: [
      {
        id: "camiseta-gucci-1",
        name: "Camiseta Vintage Logo",
        description: "Camiseta con logo vintage inspirado en la casa italiana.",
        price: 30,
        originalPrice: 50,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
  },
  Pantalon: {
    Nike: [
      {
        id: "pantalon-nike-1",
        name: "Jogger Sportswear",
        description: "Pantalon jogger con punos elasticos. Comodidad diaria.",
        price: 30,
        originalPrice: 50,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
    Adidas: [
      {
        id: "pantalon-adidas-1",
        name: "Track Pants Clasico",
        description: "Pantalon deportivo clasico con las tres rayas laterales.",
        price: 28,
        originalPrice: 48,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
  },
}

export const relojesData: Product[] = [
  {
    id: "reloj-submariner",
    name: "Reloj Submariner Style",
    description: "Reloj inspirado en el Submariner. Acero inoxidable con bisel giratorio.",
    price: 45,
    originalPrice: 80,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-daytona",
    name: "Reloj Daytona Style",
    description: "Cronografo inspirado en el Daytona. Esfera negra con subdiales.",
    price: 50,
    originalPrice: 85,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-datejust",
    name: "Reloj DateJust Style",
    description: "Reloj clasico con calendario. Correa metalica jubilee.",
    price: 42,
    originalPrice: 75,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-royal-oak",
    name: "Reloj Royal Oak Style",
    description: "Inspirado en el iconico Royal Oak. Bisel octogonal en acero.",
    price: 55,
    originalPrice: 95,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-nautilus",
    name: "Reloj Nautilus Style",
    description: "Diseno inspirado en el Nautilus. Esfera azul con textura horizontal.",
    price: 52,
    originalPrice: 90,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-santos",
    name: "Reloj Santos Style",
    description: "Reloj cuadrado inspirado en el Santos. Elegancia atemporal.",
    price: 48,
    originalPrice: 82,
    image: "/images/reloj-luxury.jpg",
  },
]

export const perfumesData: Product[] = [
  {
    id: "perfume-bleu",
    name: "Eau de Parfum Blue Intense",
    description: "Fragancia masculina amaderada con notas citricas. Inspirado en Chanel Bleu.",
    price: 28,
    originalPrice: 50,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-sauvage",
    name: "Sauvage Style EDT",
    description: "Fragancia fresca y especiada. Inspirado en Dior Sauvage.",
    price: 30,
    originalPrice: 55,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-good-girl",
    name: "Good Girl Style",
    description: "Fragancia femenina sensual con notas de jazmin y cacao.",
    price: 28,
    originalPrice: 48,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-one-million",
    name: "One Million Style",
    description: "Fragancia masculina dulce y especiada. Irresistible.",
    price: 25,
    originalPrice: 45,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-coco",
    name: "Coco Mademoiselle Style",
    description: "Fragancia femenina fresca y oriental. Elegancia parisina.",
    price: 32,
    originalPrice: 55,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-acqua",
    name: "Acqua Di Gio Style",
    description: "Fragancia acuatica y fresca. Perfecta para el dia a dia.",
    price: 26,
    originalPrice: 48,
    image: "/images/perfume-luxury.jpg",
  },
]
