import { Product } from "./types"

export const PROVINCIAS_ESPANA = [
  "A Coruna",
  "Alava",
  "Albacete",
  "Alicante",
  "Almeria",
  "Asturias",
  "Avila",
  "Badajoz",
  "Barcelona",
  "Burgos",
  "Caceres",
  "Cadiz",
  "Cantabria",
  "Castellon",
  "Ceuta",
  "Ciudad Real",
  "Cordoba",
  "Cuenca",
  "Girona",
  "Granada",
  "Guadalajara",
  "Guipuzcoa",
  "Huelva",
  "Huesca",
  "Illes Balears",
  "Jaen",
  "La Rioja",
  "Las Palmas",
  "Leon",
  "Lleida",
  "Lugo",
  "Madrid",
  "Malaga",
  "Melilla",
  "Murcia",
  "Navarra",
  "Ourense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Vizcaya",
  "Zamora",
  "Zaragoza",
]

export const zapatillasData: Record<string, Product[]> = {
  Nike: [
    {
      id: "nike-air-max",
      name: "Air Max 90",
      description: "Zapatillas deportivas con amortiguacion Air visible. Estilo urbano premium.",
      price: 65,
      originalPrice: 110,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["38", "39", "40", "41", "42", "43", "44"],
    },
    {
      id: "nike-dunk-low",
      name: "Dunk Low Retro",
      description: "Clasicas zapatillas de baloncesto reinventadas para el street style.",
      price: 60,
      originalPrice: 100,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["38", "39", "40", "41", "42", "43", "44"],
    },
    {
      id: "nike-air-force",
      name: "Air Force 1 '07",
      description: "El icono atemporal del streetwear. Piel premium y suela Air.",
      price: 55,
      originalPrice: 95,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["38", "39", "40", "41", "42", "43", "44"],
    },
  ],
  "Louis Vuitton": [
    {
      id: "lv-trainer",
      name: "LV Trainer Sneaker",
      description: "Zapatilla inspirada en el diseno de alta moda. Detalles de lujo.",
      price: 70,
      originalPrice: 120,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["39", "40", "41", "42", "43", "44"],
    },
    {
      id: "lv-run-away",
      name: "Run Away Sneaker",
      description: "Combinacion de materiales premium con suela tecnica moderna.",
      price: 68,
      originalPrice: 115,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["39", "40", "41", "42", "43", "44"],
    },
  ],
  Adidas: [
    {
      id: "adidas-samba",
      name: "Samba OG",
      description: "El clasico del futbol sala convertido en icono de moda.",
      price: 55,
      originalPrice: 90,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["38", "39", "40", "41", "42", "43", "44"],
    },
    {
      id: "adidas-yeezy",
      name: "Yeezy Boost 350",
      description: "Diseno futurista con tecnologia Boost. Comodidad extrema.",
      price: 70,
      originalPrice: 110,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["39", "40", "41", "42", "43", "44"],
    },
  ],
  "New Balance": [
    {
      id: "nb-550",
      name: "550 Retro",
      description: "Zapatilla retro basketball con estilo contemporaneo.",
      price: 58,
      originalPrice: 95,
      image: "/images/zapatillas-nike.jpg",
      sizes: ["38", "39", "40", "41", "42", "43", "44"],
    },
  ],
}

export const accesoriosData: Product[] = [
  {
    id: "gorra-premium-1",
    name: "Gorra Snapback Premium",
    description: "Gorra ajustable con bordado de alta calidad. Material resistente y comodo.",
    price: 18,
    originalPrice: 30,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "gorra-dad-hat",
    name: "Dad Hat Classic",
    description: "Gorra estilo dad hat con cierre de hebilla metalica. Look casual elegante.",
    price: 15,
    originalPrice: 25,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "bolso-crossbody",
    name: "Bolso Crossbody Urban",
    description: "Bolso cruzado inspirado en marcas de lujo. Perfecto para el dia a dia.",
    price: 35,
    originalPrice: 60,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "bolso-tote",
    name: "Tote Bag Premium",
    description: "Bolso tote de gran capacidad con acabados de alta calidad.",
    price: 40,
    originalPrice: 70,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "cinturon-lujo",
    name: "Cinturon Piel Premium",
    description: "Cinturon de piel sintetica con hebilla metalica grabada.",
    price: 22,
    originalPrice: 38,
    image: "/images/accesorio-gorra.jpg",
  },
  {
    id: "gafas-sol",
    name: "Gafas de Sol Aviator",
    description: "Gafas de sol estilo aviador con proteccion UV400. Marco metalico.",
    price: 20,
    originalPrice: 35,
    image: "/images/accesorio-gorra.jpg",
  },
]

export const ropaData: Record<string, Record<string, Product[]>> = {
  Chandal: {
    Nike: [
      {
        id: "chandal-nike-1",
        name: "Chandal Deportivo Negro",
        description: "Chandal completo (chaqueta + pantalon) en negro. Tejido transpirable.",
        price: 55,
        originalPrice: 90,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
      {
        id: "chandal-nike-2",
        name: "Chandal Tech Fleece",
        description: "Chandal de forro polar tecnico. Ligero y abrigado.",
        price: 65,
        originalPrice: 110,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
    "Louis Vuitton": [
      {
        id: "chandal-lv-1",
        name: "Chandal Monogram",
        description: "Chandal inspirado en la linea monogram. Acabados premium.",
        price: 70,
        originalPrice: 120,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
    Adidas: [
      {
        id: "chandal-adidas-1",
        name: "Chandal 3 Rayas Classic",
        description: "El clasico chandal con las tres rayas iconicas.",
        price: 50,
        originalPrice: 85,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
  },
  Chaqueta: {
    Nike: [
      {
        id: "chaqueta-nike-1",
        name: "Windrunner Jacket",
        description: "Chaqueta cortavientos ligera y resistente al agua.",
        price: 45,
        originalPrice: 75,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
    "The North Face": [
      {
        id: "chaqueta-tnf-1",
        name: "Puffer Jacket 700",
        description: "Chaqueta acolchada inspirada en el modelo 700. Abrigada y estilosa.",
        price: 60,
        originalPrice: 100,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
  },
  Camiseta: {
    Nike: [
      {
        id: "camiseta-nike-1",
        name: "Camiseta Essential Swoosh",
        description: "Camiseta basica de algodon con logo bordado.",
        price: 18,
        originalPrice: 30,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
    "Louis Vuitton": [
      {
        id: "camiseta-lv-1",
        name: "Camiseta Logo Estampado",
        description: "Camiseta premium con estampado de logo. Algodon 100%.",
        price: 28,
        originalPrice: 45,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
    Gucci: [
      {
        id: "camiseta-gucci-1",
        name: "Camiseta Vintage Logo",
        description: "Camiseta con logo vintage inspirado en la casa italiana.",
        price: 30,
        originalPrice: 50,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
  },
  Pantalon: {
    Nike: [
      {
        id: "pantalon-nike-1",
        name: "Jogger Sportswear",
        description: "Pantalon jogger con punos elasticos. Comodidad diaria.",
        price: 30,
        originalPrice: 50,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
    Adidas: [
      {
        id: "pantalon-adidas-1",
        name: "Track Pants Clasico",
        description: "Pantalon deportivo clasico con las tres rayas laterales.",
        price: 28,
        originalPrice: 48,
        image: "/images/ropa-chandal.jpg",
        sizes: ["S", "M", "L", "XL", "XXL"],
      },
    ],
  },
}

export const relojesData: Product[] = [
  {
    id: "reloj-submariner",
    name: "Reloj Submariner Style",
    description: "Reloj inspirado en el Submariner. Acero inoxidable con bisel giratorio.",
    price: 45,
    originalPrice: 80,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-daytona",
    name: "Reloj Daytona Style",
    description: "Cronografo inspirado en el Daytona. Esfera negra con subdiales.",
    price: 50,
    originalPrice: 85,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-datejust",
    name: "Reloj DateJust Style",
    description: "Reloj clasico con calendario. Correa metalica jubilee.",
    price: 42,
    originalPrice: 75,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-royal-oak",
    name: "Reloj Royal Oak Style",
    description: "Inspirado en el iconico Royal Oak. Bisel octogonal en acero.",
    price: 55,
    originalPrice: 95,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-nautilus",
    name: "Reloj Nautilus Style",
    description: "Diseno inspirado en el Nautilus. Esfera azul con textura horizontal.",
    price: 52,
    originalPrice: 90,
    image: "/images/reloj-luxury.jpg",
  },
  {
    id: "reloj-santos",
    name: "Reloj Santos Style",
    description: "Reloj cuadrado inspirado en el Santos. Elegancia atemporal.",
    price: 48,
    originalPrice: 82,
    image: "/images/reloj-luxury.jpg",
  },
]

export const perfumesData: Product[] = [
  {
    id: "perfume-bleu",
    name: "Eau de Parfum Blue Intense",
    description: "Fragancia masculina amaderada con notas citricas. Inspirado en Chanel Bleu.",
    price: 28,
    originalPrice: 50,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-sauvage",
    name: "Sauvage Style EDT",
    description: "Fragancia fresca y especiada. Inspirado en Dior Sauvage.",
    price: 30,
    originalPrice: 55,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-good-girl",
    name: "Good Girl Style",
    description: "Fragancia femenina sensual con notas de jazmin y cacao.",
    price: 28,
    originalPrice: 48,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-one-million",
    name: "One Million Style",
    description: "Fragancia masculina dulce y especiada. Irresistible.",
    price: 25,
    originalPrice: 45,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-coco",
    name: "Coco Mademoiselle Style",
    description: "Fragancia femenina fresca y oriental. Elegancia parisina.",
    price: 32,
    originalPrice: 55,
    image: "/images/perfume-luxury.jpg",
  },
  {
    id: "perfume-acqua",
    name: "Acqua Di Gio Style",
    description: "Fragancia acuatica y fresca. Perfecta para el dia a dia.",
    price: 26,
    originalPrice: 48,
    image: "/images/perfume-luxury.jpg",
  },
]
